services:
  threads_mongodb:
    image: mongo
    container_name: threads_mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${THREADS_DB}
    ports:
      - 27018:27017
    volumes:
      - threads_mongodb_data:/data/db
      - ./mongodb-init:/docker-entrypoint-initdb.d

  web_db_root:
    image: mongo-express
    container_name: web_db_root
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${ROOT_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${ROOT_PASSWORD}
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_MONGODB_SERVER: threads_mongodb
      ME_CONFIG_MONGODB_URL: ${ROOT_URL}
      # ME_CONFIG_BASICAUTH: false
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: mlIm*mrAh@aYiE4hw

  web_db_dev:
    image: mongo-express
    container_name: web_db_dev
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "false"
      ME_CONFIG_MONGODB_SERVER: threads_mongodb
      ME_CONFIG_MONGODB_AUTH_DATABASE: threads_db
      ME_CONFIG_MONGODB_AUTH_USERNAME: ${DEV_USER}
      ME_CONFIG_MONGODB_AUTH_PASSWORD: ${DEV_PASSWORD}
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: mlIm*mrAh@aYiE4hw
      ME_CONFIG_MONGODB_URL: ${DEV_URL}

  backup:
    image: alpine
    tty: false
    environment:
      - TARGET=threads_mongodb_data
    volumes:
      - threads_mongodb_data:/volume
      - ./backup:/backup
    command: sh -c "tar -cjf /backup/$${TARGET}.tar.bz2 -C /volume ./"

  restore:
    image: alpine
    environment:
      - SOURCE=threads_mongodb_data
    volumes:
      - threads_mongodb_data:/volume
      - ./backup:/backup
    command: sh -c "rm -rf /volume/* /volume/..?* /volume/.[!.]* ; tar -C /volume/ -xjf /backup/$${SOURCE}.tar.bz2"
  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    environment:
      - REDIS_PASSWORD=admin

volumes:
  threads_mongodb_data:
   redis-data:
    driver: local
