version: "3.8"

services:
  auth-service:
    container_name: auth-service
    build:
      context: ./../../auth-service
      dockerfile: dev.Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    volumes:
      - .:/usr/src/app
